// <auto-generated />
using System;
using Juple.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Juple.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JupleDbContext))]
    [Migration("20260906040950_AddRecentlyOpenedItems")]
    partial class AddRecentlyOpenedItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Juple.Domain.Categories.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_UserId_Name");

                    b.HasIndex("UserId", "SortOrder", "Id")
                        .HasDatabaseName("IX_Categories_UserId_SortOrder_Id");

                    b.ToTable("Categories", "categories");
                });

            modelBuilder.Entity("Juple.Domain.Collections.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("UX_Collections_UserId_NameNormalized");

                    b.HasIndex("UserId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("IX_Collections_UserId_CreatedAtUtc_Id");

                    b.ToTable("Collections", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_CollectionItems_ItemId");

                    b.HasIndex("CollectionId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionItems_CollectionId_ItemId");

                    b.HasIndex("CollectionId", "AddedAtUtc", "ItemId")
                        .HasDatabaseName("IX_CollectionItems_CollectionId_AddedAtUtc_ItemId");

                    b.ToTable("CollectionItems", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionShares_CollectionId_Active")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionShares_PublicId");

                    b.ToTable("CollectionShares", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ExternalIdentities_UserId");

                    b.HasIndex("TenantId", "ObjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExternalIdentities_TenantId_ObjectId");

                    b.ToTable("ExternalIdentities", "identity");
                });

            modelBuilder.Entity("Juple.Domain.Images.ItemImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlobName")
                        .IsUnique()
                        .HasDatabaseName("UX_ItemImages_BlobName");

                    b.HasIndex("ItemId", "SortOrder", "Id")
                        .HasDatabaseName("IX_ItemImages_ItemId_SortOrder_Id");

                    b.ToTable("ItemImages", "images", t =>
                        {
                            t.HasCheckConstraint("CK_ItemImages_ByteLength_Positive", "[ByteLength] > 0");

                            t.HasCheckConstraint("CK_ItemImages_SortOrder_NonNegative", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Items.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Memo")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("StateChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Items_CategoryId");

                    b.HasIndex("UserId", "SavedAtUtc", "Id")
                        .HasDatabaseName("IX_Items_UserId_SavedAtUtc_Id");

                    b.HasIndex("UserId", "State", "StateChangedAtUtc", "Id")
                        .HasDatabaseName("IX_Items_UserId_State_StateChangedAtUtc_Id");

                    b.ToTable("Items", "items", t =>
                        {
                            t.HasCheckConstraint("CK_Items_Url_MaxLength", "DATALENGTH([Url]) <= 8192");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Items.ItemSaveRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_ItemSaveRequests_UserId_ClientRequestId");

                    b.ToTable("ItemSaveRequests", "items", t =>
                        {
                            t.HasCheckConstraint("CK_ItemSaveRequests_Url_MaxLength", "DATALENGTH([Url]) <= 8192");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Items.RecentlyOpenedItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastOpenedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_RecentlyOpenedItems_UserId_ItemId");

                    b.HasIndex("UserId", "LastOpenedAtUtc", "ItemId")
                        .HasDatabaseName("IX_RecentlyOpenedItems_UserId_LastOpenedAtUtc_ItemId");

                    b.ToTable("RecentlyOpenedItems", "items");
                });

            modelBuilder.Entity("Juple.Domain.Purchases.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyCode")
                        .IsUnicode(false)
                        .HasColumnType("char(3)");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Memo")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("RepeatPurchaseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Store")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Variant")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_Purchases_ItemId");

                    b.HasIndex("RepeatPurchaseId")
                        .HasDatabaseName("IX_Purchases_RepeatPurchaseId");

                    b.HasIndex("UserId", "PurchaseDate", "Id")
                        .HasDatabaseName("IX_Purchases_UserId_PurchaseDate_Id");

                    b.ToTable("Purchases", "purchases", t =>
                        {
                            t.HasCheckConstraint("CK_Purchases_Amount_CurrencyCode_Together", "([Amount] IS NULL AND [CurrencyCode] IS NULL) OR ([Amount] IS NOT NULL AND [CurrencyCode] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Purchases_Amount_NonNegative", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_Purchases_ProductName_NotWhitespaceOnly", "PATINDEX('%[^' + CHAR(9) + CHAR(10) + CHAR(13) + ' ]%', [ProductName]) > 0");

                            t.HasCheckConstraint("CK_Purchases_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Purchases.RepeatPurchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("IntervalUnit")
                        .HasColumnType("tinyint");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReminderEnabled")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("NextPurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReminderLeadDays")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_RepeatPurchases_ItemId");

                    b.HasIndex("UserId", "IsEnabled", "NextPurchaseDate", "Id")
                        .HasDatabaseName("IX_RepeatPurchases_UserId_IsEnabled_NextPurchaseDate_Id");

                    b.ToTable("RepeatPurchases", "purchases", t =>
                        {
                            t.HasCheckConstraint("CK_RepeatPurchases_IntervalUnit_Valid", "[IntervalUnit] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_RepeatPurchases_IntervalValue_Positive", "[IntervalValue] > 0");

                            t.HasCheckConstraint("CK_RepeatPurchases_ProductName_NotWhitespaceOnly", "PATINDEX('%[^' + CHAR(9) + CHAR(10) + CHAR(13) + ' ]%', [ProductName]) > 0");

                            t.HasCheckConstraint("CK_RepeatPurchases_ReminderLeadDays_NonNegative", "[ReminderLeadDays] >= 0");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultCurrencyCode")
                        .IsUnicode(false)
                        .HasColumnType("char(3)");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("Juple.Domain.Categories.Category", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.Collection", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionItem", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionShare", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Images.ItemImage", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Items.Item", b =>
                {
                    b.HasOne("Juple.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Items.ItemSaveRequest", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Items.RecentlyOpenedItem", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Purchases.Purchase", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Juple.Domain.Purchases.RepeatPurchase", null)
                        .WithMany()
                        .HasForeignKey("RepeatPurchaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Purchases.RepeatPurchase", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
