// <auto-generated />
using System;
using Juple.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Juple.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JupleDbContext))]
    partial class JupleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Juple.Domain.Collections.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Folder");

                    b.Property<string>("IconImageBlobName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LockPasswordChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LockPasswordHash")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("LockVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("UX_Collections_UserId_NameNormalized");

                    b.HasIndex("UserId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("IX_Collections_UserId_CreatedAtUtc_Id");

                    b.HasIndex("UserId", "DeletedAtUtc", "Id")
                        .HasDatabaseName("IX_Collections_UserId_DeletedAtUtc_Id");

                    b.ToTable("Collections", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionCollaborator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CollectionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionCollaborators_CollectionId_UserId");

                    b.HasIndex("UserId", "CollectionId")
                        .HasDatabaseName("IX_CollectionCollaborators_UserId_CollectionId");

                    b.ToTable("CollectionCollaborators", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionFavorite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("IX_CollectionFavorites_CollectionId");

                    b.HasIndex("UserId", "CollectionId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionFavorites_UserId_CollectionId");

                    b.ToTable("CollectionFavorites", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionInvitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("InvitedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("InvitedUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("CollectionId", "InvitedUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionInvitations_CollectionId_InvitedUserId_Pending")
                        .HasFilter("[Status] = 'Pending'");

                    b.HasIndex("CollectionId", "Status")
                        .HasDatabaseName("IX_CollectionInvitations_CollectionId_Status");

                    b.HasIndex("InvitedUserId", "Status")
                        .HasDatabaseName("IX_CollectionInvitations_InvitedUserId_Status");

                    b.ToTable("CollectionInvitations", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("AddedByUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("AddedViaPublicShare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_CollectionItems_ItemId");

                    b.HasIndex("CollectionId", "AddedByUserId")
                        .HasDatabaseName("IX_CollectionItems_CollectionId_AddedByUserId");

                    b.HasIndex("CollectionId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionItems_CollectionId_ItemId");

                    b.HasIndex("CollectionId", "SortOrder", "Id")
                        .HasDatabaseName("IX_CollectionItems_CollectionId_SortOrder_Id");

                    b.ToTable("CollectionItems", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionLinkSubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviewImageUrl")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubmittedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("UrlHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<bool>("ViaPublicShare")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_CollectionLinkSubmissions_ItemId");

                    b.HasIndex("SubmittedByUserId")
                        .HasDatabaseName("IX_CollectionLinkSubmissions_SubmittedByUserId");

                    b.HasIndex("CollectionId", "Id")
                        .HasDatabaseName("IX_CollectionLinkSubmissions_CollectionId_Id");

                    b.HasIndex("CollectionId", "UrlHash")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionLinkSubmissions_CollectionId_UrlHash");

                    b.ToTable("CollectionLinkSubmissions", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionMergeCreatedMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("MergeOperationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CollectionItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionMergeCreatedMemberships_CollectionItemId");

                    b.HasIndex("MergeOperationId")
                        .HasDatabaseName("IX_CollectionMergeCreatedMemberships_MergeOperationId");

                    b.ToTable("CollectionMergeCreatedMemberships", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionMergeOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SourceCollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetCollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UndoneAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OperationToken")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionMergeOperations_OperationToken");

                    b.HasIndex("SourceCollectionId");

                    b.HasIndex("TargetCollectionId");

                    b.HasIndex("UserId");

                    b.ToTable("CollectionMergeOperations", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionNotificationPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("NewItemNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CollectionNotificationPreferences_UserId");

                    b.HasIndex("CollectionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionNotificationPreferences_CollectionId_UserId");

                    b.ToTable("CollectionNotificationPreferences", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Read");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionShares_CollectionId_Active")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionShares_PublicId");

                    b.ToTable("CollectionShares", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionSharePassword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EncryptedPassword")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("PasswordVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionSharePasswords_CollectionId");

                    b.ToTable("CollectionSharePasswords", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionUnlockThrottle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("WindowStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId", "SubjectKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CollectionUnlockThrottles_CollectionId_SubjectKey");

                    b.ToTable("CollectionUnlockThrottles", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Collections.UserCollectionLockSettings", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedChangeAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("FailedChangeWindowStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("UserId");

                    b.ToTable("UserCollectionLockSettings", "collections");
                });

            modelBuilder.Entity("Juple.Domain.Friends.Friendship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("RequestedByUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<long>("UserHighId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserLowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("UserHighId")
                        .HasDatabaseName("IX_Friendships_UserHighId");

                    b.HasIndex("UserLowId", "UserHighId")
                        .IsUnique()
                        .HasDatabaseName("UX_Friendships_UserLowId_UserHighId");

                    b.ToTable("Friendships", "users", t =>
                        {
                            t.HasCheckConstraint("CK_Friendships_CanonicalPair", "[UserLowId] < [UserHighId]");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Friends.FriendshipNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FriendshipId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("FriendshipId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_FriendshipNotes_FriendshipId_UserId");

                    b.ToTable("FriendshipNotes", "users");
                });

            modelBuilder.Entity("Juple.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ExternalIdentities_UserId");

                    b.HasIndex("TenantId", "ObjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExternalIdentities_TenantId_ObjectId");

                    b.ToTable("ExternalIdentities", "identity");
                });

            modelBuilder.Entity("Juple.Domain.Images.AccountDeletionBlobCleanup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("BlobPrefix")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FinalSweepAfterUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastErrorCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AccountDeletionBlobCleanups", "images");
                });

            modelBuilder.Entity("Juple.Domain.Images.ItemImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlobName")
                        .IsUnique()
                        .HasDatabaseName("UX_ItemImages_BlobName");

                    b.HasIndex("ItemId", "SortOrder", "Id")
                        .HasDatabaseName("IX_ItemImages_ItemId_SortOrder_Id");

                    b.ToTable("ItemImages", "images", t =>
                        {
                            t.HasCheckConstraint("CK_ItemImages_ByteLength_Positive", "[ByteLength] > 0");

                            t.HasCheckConstraint("CK_ItemImages_SortOrder_NonNegative", "[SortOrder] >= 0");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Items.InstagramMetadataRetryTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastErrorCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_InstagramMetadataRetryTasks_ItemId");

                    b.HasIndex("NextAttemptAtUtc")
                        .HasDatabaseName("IX_InstagramMetadataRetryTasks_NextAttemptAtUtc");

                    b.ToTable("InstagramMetadataRetryTasks", "items");
                });

            modelBuilder.Entity("Juple.Domain.Items.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoverImageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Memo")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PreviewImageUrl")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeletedAtUtc", "Id")
                        .HasDatabaseName("IX_Items_UserId_DeletedAtUtc_Id");

                    b.HasIndex("UserId", "SavedAtUtc", "Id")
                        .HasDatabaseName("IX_Items_UserId_SavedAtUtc_Id");

                    b.ToTable("Items", "items", t =>
                        {
                            t.HasCheckConstraint("CK_Items_Url_MaxLength", "DATALENGTH([Url]) <= 8192");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Items.ItemSaveRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_ItemSaveRequests_UserId_ClientRequestId");

                    b.ToTable("ItemSaveRequests", "items", t =>
                        {
                            t.HasCheckConstraint("CK_ItemSaveRequests_Url_MaxLength", "DATALENGTH([Url]) <= 8192");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Items.RecentlyOpenedItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastOpenedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_RecentlyOpenedItems_UserId_ItemId");

                    b.HasIndex("UserId", "LastOpenedAtUtc", "ItemId")
                        .HasDatabaseName("IX_RecentlyOpenedItems_UserId_LastOpenedAtUtc_ItemId");

                    b.ToTable("RecentlyOpenedItems", "items");
                });

            modelBuilder.Entity("Juple.Domain.Notifications.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DedupKey")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("int");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductNameSnapshot")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("RepeatPurchaseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("IX_Notifications_ActorUserId")
                        .HasFilter("[ActorUserId] IS NOT NULL");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Notifications_DedupKey")
                        .HasFilter("[DedupKey] IS NOT NULL");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_Notifications_ItemId");

                    b.HasIndex("RepeatPurchaseId")
                        .HasDatabaseName("IX_Notifications_RepeatPurchaseId");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .HasDatabaseName("IX_Notifications_PendingDispatch")
                        .HasFilter("[DispatchedAtUtc] IS NULL AND [DedupKey] IS NOT NULL");

                    b.HasIndex("UserId", "ReadAtUtc")
                        .HasDatabaseName("IX_Notifications_UserId_ReadAtUtc");

                    b.HasIndex("Type", "RepeatPurchaseId", "DueDate")
                        .IsUnique()
                        .HasDatabaseName("UX_Notifications_Type_RepeatPurchaseId_DueDate")
                        .HasFilter("[RepeatPurchaseId] IS NOT NULL AND [DueDate] IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("IX_Notifications_UserId_CreatedAtUtc_Id");

                    b.ToTable("Notifications", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Type_Valid", "[Type] IN (0, 1, 2, 3, 4, 5, 6, 7)");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Notifications.NotificationDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderMessageId")
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("PushDeviceRegistrationId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PushDeviceRegistrationId");

                    b.HasIndex("NotificationId", "PushDeviceRegistrationId")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationDeliveries_NotificationId_PushDeviceRegistrationId");

                    b.ToTable("NotificationDeliveries", "notifications", t =>
                        {
                            t.HasCheckConstraint("CK_NotificationDeliveries_Status_Valid", "[Status] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Purchases.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrencyCode")
                        .IsUnicode(false)
                        .HasColumnType("char(3)");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Memo")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long?>("RepeatPurchaseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Store")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Variant")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_Purchases_ItemId");

                    b.HasIndex("RepeatPurchaseId")
                        .HasDatabaseName("IX_Purchases_RepeatPurchaseId");

                    b.HasIndex("UserId", "PurchaseDate", "Id")
                        .HasDatabaseName("IX_Purchases_UserId_PurchaseDate_Id");

                    b.ToTable("Purchases", "purchases", t =>
                        {
                            t.HasCheckConstraint("CK_Purchases_Amount_CurrencyCode_Together", "([Amount] IS NULL AND [CurrencyCode] IS NULL) OR ([Amount] IS NOT NULL AND [CurrencyCode] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Purchases_Amount_NonNegative", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_Purchases_ProductName_NotWhitespaceOnly", "PATINDEX('%[^' + CHAR(9) + CHAR(10) + CHAR(13) + ' ]%', [ProductName]) > 0");

                            t.HasCheckConstraint("CK_Purchases_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Purchases.RepeatPurchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("IntervalUnit")
                        .HasColumnType("tinyint");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReminderEnabled")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("NextPurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReminderLeadDays")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_RepeatPurchases_ItemId");

                    b.HasIndex("UserId", "IsEnabled", "NextPurchaseDate", "Id")
                        .HasDatabaseName("IX_RepeatPurchases_UserId_IsEnabled_NextPurchaseDate_Id");

                    b.ToTable("RepeatPurchases", "purchases", t =>
                        {
                            t.HasCheckConstraint("CK_RepeatPurchases_IntervalUnit_Valid", "[IntervalUnit] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_RepeatPurchases_IntervalValue_Positive", "[IntervalValue] > 0");

                            t.HasCheckConstraint("CK_RepeatPurchases_ProductName_NotWhitespaceOnly", "PATINDEX('%[^' + CHAR(9) + CHAR(10) + CHAR(13) + ' ]%', [ProductName]) > 0");

                            t.HasCheckConstraint("CK_RepeatPurchases_ReminderLeadDays_NonNegative", "[ReminderLeadDays] >= 0");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Push.PushDeviceRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.Property<byte>("Platform")
                        .HasColumnType("tinyint");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "InstallationId")
                        .IsUnique()
                        .HasDatabaseName("UX_PushDeviceRegistrations_Platform_InstallationId");

                    b.HasIndex("UserId", "IsEnabled")
                        .HasDatabaseName("IX_PushDeviceRegistrations_UserId_IsEnabled");

                    b.ToTable("PushDeviceRegistrations", "push", t =>
                        {
                            t.HasCheckConstraint("CK_PushDeviceRegistrations_Platform_Valid", "[Platform] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Juple.Domain.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultCurrencyCode")
                        .IsUnicode(false)
                        .HasColumnType("char(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Free");

                    b.Property<string>("PreferredLocale")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<string>("ProfileImageBlobName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PublicCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_PublicCode");

                    b.ToTable("Users", "users");
                });

            modelBuilder.Entity("Juple.Domain.Collections.Collection", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionCollaborator", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionFavorite", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionInvitation", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionItem", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionLinkSubmission", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionMergeCreatedMembership", b =>
                {
                    b.HasOne("Juple.Domain.Collections.CollectionItem", null)
                        .WithMany()
                        .HasForeignKey("CollectionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Collections.CollectionMergeOperation", null)
                        .WithMany()
                        .HasForeignKey("MergeOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionMergeOperation", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("SourceCollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("TargetCollectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionNotificationPreference", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionShare", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionSharePassword", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.CollectionUnlockThrottle", b =>
                {
                    b.HasOne("Juple.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Collections.UserCollectionLockSettings", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Juple.Domain.Collections.UserCollectionLockSettings", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Friends.Friendship", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserHighId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserLowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Friends.FriendshipNote", b =>
                {
                    b.HasOne("Juple.Domain.Friends.Friendship", null)
                        .WithMany()
                        .HasForeignKey("FriendshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Images.ItemImage", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Items.InstagramMetadataRetryTask", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Items.Item", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Items.ItemSaveRequest", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Items.RecentlyOpenedItem", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Juple.Domain.Purchases.RepeatPurchase", null)
                        .WithMany()
                        .HasForeignKey("RepeatPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Notifications.NotificationDelivery", b =>
                {
                    b.HasOne("Juple.Domain.Notifications.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juple.Domain.Push.PushDeviceRegistration", null)
                        .WithMany()
                        .HasForeignKey("PushDeviceRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Purchases.Purchase", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Juple.Domain.Purchases.RepeatPurchase", null)
                        .WithMany()
                        .HasForeignKey("RepeatPurchaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Purchases.RepeatPurchase", b =>
                {
                    b.HasOne("Juple.Domain.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Juple.Domain.Push.PushDeviceRegistration", b =>
                {
                    b.HasOne("Juple.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
