<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Juple.Application\Juple.Application.csproj" />
    <ProjectReference Include="..\Juple.Domain\Juple.Domain.csproj" />
  </ItemGroup>

</Project>
